"use client";

import { RepositorySummary } from "@/lib/api";

interface HandoverPageProps {
  repo: RepositorySummary;
  onBack: () => void;
  handoverState: "not_started" | "in_progress" | "prepared";
  developerNotes: string;
  onStateChange: (state: "not_started" | "in_progress" | "prepared") => void;
  onNotesChange: (notes: string) => void;
}

export default function HandoverPage({
  repo,
  onBack,
  handoverState,
  developerNotes,
  onStateChange,
  onNotesChange,
}: HandoverPageProps) {
  // Define metadata of what is included
  const sections = [
    {
      id: "project_overview",
      title: "Project Overview",
      description: "Understand what this repository does.",
      details: "A comprehensive summary of the project purpose, architecture patterns, and domain model.",
      placeholder: "This section will be automatically generated by analyzing repository README, structure, and documentation files.",
    },
    {
      id: "start_here",
      title: "Start Here",
      description: "Know where to begin exploring the codebase.",
      details: "Key entry points, bootstrap procedures, and recommended onboarding tasks for incoming developers.",
      placeholder: "This section will identify main files, startup scripts, and configurations to guide the onboarding developer.",
    },
    {
      id: "development_history",
      title: "Development History",
      description: "Understand what has changed recently.",
      details: "Summary of recent commit trends, major architectural shifts, and frequently modified paths.",
      placeholder: "This section will parse git history to identify recent changes and key contributors.",
    },
    {
      id: "important_areas",
      title: "Important Areas",
      description: "Identify important parts of the project.",
      details: "Modules with high complexity, core business logic, or critical integration boundaries.",
      placeholder: "This section will run code analysis to pinpoint critical areas requiring attention.",
    },
    {
      id: "known_risks",
      title: "Known Risks",
      description: "Understand areas that may require attention.",
      details: "Technical debt, weak test coverage, deprecated dependencies, or fragile custom modules.",
      placeholder: "This section will highlights potential hotspots, bug-prone files, and test coverage gaps.",
    },
    {
      id: "unfinished_work",
      title: "Unfinished Work",
      description: "Capture work that may still be in progress.",
      details: "Pending branches, TODO comments in code, and outstanding pull requests or issue links.",
      placeholder: "This section will extract inline TODOs, active draft branches, and incomplete modules.",
    },
  ];

  return (
    <div className="mx-auto max-w-5xl px-6 py-12 select-none">
      {/* Back Button & Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-baseline sm:justify-between mb-10">
        <div className="flex items-baseline gap-4">
          <button
            onClick={onBack}
            className="rounded-none border border-border-muted bg-surface-secondary p-1.5 text-text-secondary hover:text-text-primary hover:border-border-strong transition-all duration-150 cursor-pointer outline-none focus-visible:ring-1 focus-visible:ring-brand-accent"
            title="Back to Repository details"
          >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-3.5 w-3.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
            </svg>
          </button>
          <div>
            <span className="text-[10px] font-mono font-bold tracking-widest text-text-muted uppercase">SECOND COMMIT</span>
            <div className="flex items-baseline gap-2.5 mt-1.5">
              <h1 className="text-3xl font-outfit text-text-primary font-extrabold tracking-tight">Repository Handover</h1>
              <span className="text-xs font-mono text-brand-accent">/ {repo.name}</span>
            </div>
            <p className="text-[10px] text-text-muted font-mono mt-1">{repo.description || "No description available"}</p>
          </div>
        </div>
      </div>

      {/* Handover Status Section */}
      <div className="border border-border-muted bg-surface-base p-8 mb-12 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="flex-1">
            <span className="text-[9px] font-mono tracking-widest uppercase text-text-muted font-bold block mb-2">HANDOVER STATUS</span>
            {handoverState === "not_started" && (
              <div>
                <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-none border border-border-strong bg-surface-secondary text-text-secondary text-[10px] font-mono font-bold uppercase mb-4">
                  <span className="h-1.5 w-1.5 rounded-full bg-text-muted" />
                  Not prepared yet
                </div>
                <p className="text-sm text-text-secondary font-sans leading-relaxed">
                  Prepare a knowledge package for the next developer who takes over this repository. It will outline codebase structure, recent history, developer notes, and active context.
                </p>
              </div>
            )}
            {handoverState === "in_progress" && (
              <div>
                <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-none border border-brand-accent/30 bg-brand-accent/10 text-brand-accent text-[10px] font-mono font-bold uppercase mb-4 animate-pulse">
                  <span className="h-1.5 w-1.5 rounded-full bg-brand-accent" />
                  In progress
                </div>
                <p className="text-sm text-text-secondary font-sans leading-relaxed">
                  You are building the handover guide. Add your custom context in **Developer Notes** below, review the package contents, and complete the package when ready.
                </p>
              </div>
            )}
            {handoverState === "prepared" && (
              <div>
                <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-none border border-semantic-healthy/30 bg-semantic-healthy/10 text-semantic-healthy text-[10px] font-mono font-bold uppercase mb-4">
                  <span className="h-1.5 w-1.5 rounded-full bg-semantic-healthy" />
                  Prepared & Ready
                </div>
                <p className="text-sm text-text-secondary font-sans leading-relaxed">
                  Your repository handover package is ready! This package is frozen in its current state. You can share this with incoming developers or reset it to modify contents.
                </p>
              </div>
            )}
          </div>

          <div className="flex flex-col sm:flex-row md:flex-col gap-3 justify-end shrink-0">
            {handoverState === "not_started" && (
              <button
                onClick={() => onStateChange("in_progress")}
                className="flex items-center justify-center gap-2.5 rounded-none bg-text-primary border border-text-primary text-white hover:bg-brand-accent hover:border-brand-accent px-6 py-3 text-[10px] font-mono uppercase tracking-widest transition-all duration-150 cursor-pointer shadow-sm hover:shadow-md"
              >
                Start Handover
              </button>
            )}
            {handoverState === "in_progress" && (
              <button
                onClick={() => onStateChange("prepared")}
                className="flex items-center justify-center gap-2.5 rounded-none bg-brand-accent border border-brand-accent text-white hover:bg-text-primary hover:border-text-primary px-6 py-3 text-[10px] font-mono uppercase tracking-widest transition-all duration-150 cursor-pointer shadow-sm hover:shadow-md"
              >
                Complete Handover
              </button>
            )}
            {handoverState === "prepared" && (
              <>
                <button
                  onClick={() => onStateChange("in_progress")}
                  className="flex items-center justify-center gap-2.5 rounded-none border border-border-strong bg-surface-secondary text-text-secondary hover:text-text-primary hover:border-text-primary px-6 py-2.5 text-[10px] font-mono uppercase tracking-widest transition-all duration-150 cursor-pointer"
                >
                  Edit Handover
                </button>
                <button
                  onClick={() => {
                    if (confirm("Are you sure you want to reset the handover? This will clear all developer notes.")) {
                      onNotesChange("");
                      onStateChange("not_started");
                    }
                  }}
                  className="flex items-center justify-center gap-2.5 rounded-none border border-semantic-critical/20 bg-surface-base text-semantic-critical hover:bg-semantic-critical/5 px-6 py-2.5 text-[10px] font-mono uppercase tracking-widest transition-all duration-150 cursor-pointer"
                >
                  Reset Handover
                </button>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Sections Headings */}
      <div className="mb-8 border-b border-border-muted pb-4">
        <h2 className="text-[10px] font-mono font-bold uppercase tracking-widest text-text-primary">
          {handoverState === "prepared" ? "Handover Package Contents" : "What Will Be Included"}
        </h2>
        <p className="text-[10px] text-text-secondary mt-1 font-sans">
          {handoverState === "prepared"
            ? "Frozen snapshots and developer notes for the next engineer."
            : "The knowledge modules that make up a complete repository handover."}
        </p>
      </div>

      {/* Handover Modules Grid / Stack */}
      <div className="space-y-6">
        {/* Render Auto-generated placeholder sections first */}
        {sections.map((section) => (
          <div
            key={section.id}
            className={`border p-6 rounded-none transition-all duration-200 ${
              handoverState === "prepared"
                ? "border-border-muted bg-surface-secondary/50"
                : "border-dashed border-border-strong bg-surface-secondary/20 hover:border-brand-accent/50 hover:bg-surface-secondary/40"
            }`}
          >
            <div className="flex flex-col sm:flex-row sm:items-baseline sm:justify-between gap-2 border-b border-border-muted/65 pb-3 mb-4">
              <h3 className="text-sm font-outfit text-text-primary font-bold">{section.title}</h3>
              <span className="text-[9px] font-mono tracking-wider uppercase text-text-muted">
                {handoverState === "prepared" ? "Auto-analyzed" : "System analyzed"}
              </span>
            </div>
            <p className="text-xs text-text-primary font-sans leading-relaxed mb-3">
              {section.description}
            </p>
            <p className="text-[11px] text-text-secondary font-sans leading-relaxed italic">
              {handoverState === "prepared" ? (
                <span className="text-text-muted">
                  [Analysis Complete] {section.details} (Metadata frozen)
                </span>
              ) : (
                <span className="text-text-muted">
                  {section.placeholder}
                </span>
              )}
            </p>
          </div>
        ))}

        {/* Developer Notes Section (Editable in progress, Static in prepared) */}
        <div
          className={`border p-6 rounded-none transition-all duration-200 ${
            handoverState === "prepared"
              ? "border-semantic-healthy/20 bg-surface-base"
              : handoverState === "in_progress"
              ? "border-brand-accent/30 bg-surface-base"
              : "border-dashed border-border-strong bg-surface-secondary/20"
          }`}
        >
          <div className="flex flex-col sm:flex-row sm:items-baseline sm:justify-between gap-2 border-b border-border-muted/65 pb-3 mb-4">
            <h3 className="text-sm font-outfit text-text-primary font-bold">Developer Notes</h3>
            <span className={`text-[9px] font-mono tracking-wider uppercase ${
              handoverState === "prepared"
                ? "text-semantic-healthy"
                : handoverState === "in_progress"
                ? "text-brand-accent"
                : "text-text-muted"
            }`}>
              {handoverState === "prepared" ? "Saved" : handoverState === "in_progress" ? "Interactive" : "Manual additions"}
            </span>
          </div>

          <p className="text-xs text-text-primary font-sans leading-relaxed mb-4">
            Allow the outgoing developer to add context that cannot be inferred from the repository.
          </p>

          {handoverState === "not_started" && (
            <div className="border border-border-muted bg-surface-secondary p-4 text-center">
              <p className="text-xs text-text-muted font-mono uppercase">Start Handover to enter notes</p>
            </div>
          )}

          {handoverState === "in_progress" && (
            <div className="space-y-2">
              <label htmlFor="developer-notes-input" className="text-[9px] font-mono uppercase text-text-muted tracking-wider block">
                Project Context & Notes for the Next Developer
              </label>
              <textarea
                id="developer-notes-input"
                value={developerNotes}
                onChange={(e) => onNotesChange(e.target.value)}
                placeholder="Share architecture details, deployment gotchas, custom system hooks, credentials locations (avoid plain-text secrets), or team contact details..."
                className="w-full h-32 p-3 text-xs font-sans border border-border-strong bg-surface-base text-text-primary placeholder:text-text-muted focus:border-brand-accent focus:outline-none transition-all duration-150 resize-y"
              />
              <span className="text-[9px] font-mono text-text-secondary block text-right">
                {developerNotes.length} characters written (Saved locally)
              </span>
            </div>
          )}

          {handoverState === "prepared" && (
            <div className="border border-semantic-healthy/20 bg-semantic-healthy/5 p-5">
              <span className="text-[9px] font-mono uppercase text-semantic-healthy tracking-wider block mb-2">OUTGOING DEVELOPER NOTES</span>
              {developerNotes.trim() ? (
                <div className="text-xs font-mono text-text-primary leading-relaxed whitespace-pre-wrap">
                  {developerNotes}
                </div>
              ) : (
                <p className="text-xs font-sans text-text-muted italic">
                  No custom developer notes were added to this handover.
                </p>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
