"""create_revival_requests_table

Revision ID: 1812c1061204
Revises: 8e2495f4c158
Create Date: 2026-08-31 19:38:19.207180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1812c1061204'
down_revision: Union[str, Sequence[str], None] = '8e2495f4c158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revival_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'repository_id', 'status', name='uq_requester_repo_status')
    )
    op.create_index(op.f('ix_revival_requests_repository_id'), 'revival_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_revival_requests_requester_id'), 'revival_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revival_requests_requester_id'), table_name='revival_requests')
    op.drop_index(op.f('ix_revival_requests_repository_id'), table_name='revival_requests')
    op.drop_table('revival_requests')
    # ### end Alembic commands ###
