"""add_index_to_repository_owner_id

Revision ID: 3a55fc78f7e7
Revises: 82febfd22ee8
Create Date: 2026-08-24 20:46:09.855231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a55fc78f7e7'
down_revision: Union[str, Sequence[str], None] = '82febfd22ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    # ### end Alembic commands ###
