"""add_published_to_repositories

Revision ID: 3ec83872bdc3
Revises: 3a55fc78f7e7
Create Date: 2026-08-29 11:16:24.124985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec83872bdc3'
down_revision: Union[str, Sequence[str], None] = '3a55fc78f7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'published')
    # ### end Alembic commands ###
