"""extend_repository_fields

Revision ID: 82febfd22ee8
Revises: b8d4c88fda2f
Create Date: 2026-07-26 21:27:18.740371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82febfd22ee8'
down_revision: Union[str, Sequence[str], None] = 'b8d4c88fda2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('forks', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('watchers', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('open_issues', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'pushed_at')
    op.drop_column('repositories', 'updated_at')
    op.drop_column('repositories', 'created_at')
    op.drop_column('repositories', 'size')
    op.drop_column('repositories', 'open_issues')
    op.drop_column('repositories', 'watchers')
    op.drop_column('repositories', 'forks')
    op.drop_column('repositories', 'stars')
    # ### end Alembic commands ###
